name: Build and Release for Raspberry Pi Zero 2 W

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-gnueabihf

      - name: Install rust-std for ARM
        run: rustup target add arm-unknown-linux-gnueabihf

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Build for Raspberry Pi Zero 2 W
        env:
          RUSTFLAGS: "-C linker=arm-linux-gnueabihf-gcc"
        run: cargo build --release --target=arm-unknown-linux-gnueabihf

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: release-binary
          path: target/arm-unknown-linux-gnueabihf/release/your_binary_name

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Asset
        uses: actions/download-artifact@v3
        with:
          name: release-binary
          path: .

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Release for Raspberry Pi Zero 2 W"
          draft: false
          prerelease: false
          files: your_binary_name
